// Variaveis
const nome = "Borges"

console.log(nome, 'nasceu em 1998.')
console.log('Em 2000', nome, 'conheceu Maria.')
console.log(nome, 'casou-se com Maria em 2012.')
console.log('Maria teve um filho com', nome, 'em 2015.')
console.log('O filho de', nome, 'se chama Eduardo.')

/* 
  Não podemos usar palavras reservadas como nome de variável...
  Variáveis precisam ter nomes significativos...
  Não pode iniciar o nome de uma variável com número...
  Não podem conter espaços e/ou ifem no nome das variáveis...
  Para variáveis com nome composto use notação camelCase...
  Variáveis são case-sensitive...
*/